### ISSUE TITLE
Carry enums over from Rust once duckdb has ALTER TYPE for custom types

### ISSUE THREAD

**Issue by droher** [droher/baseball.computer#2]
```
  enum_lookups:
    side: game.game_team
    doubleheader_status: game.game
    time_of_day: game.game
    game_type: game.game
    sky: game.game
    field_condition: game.game
    precipitation: game.game
    wind_direction: game.game
    entered_game_as: game.game_lineup_appearance
    frame: event.event
    baserunner: event.event_starting_base_state
    baserunning_play_type: event.event_baserunning_play
    contact: event.event_batted_ball_info
    general_location: event.event_batted_ball_info
    depth: event.event_batted_ball_info
    angle: event.event_batted_ball_info
    strength: event.event_batted_ball_info
    fielding_play: event.event_fielding_play
    flag: event.event_flag
    sequence_item: event.event_pitch
  enum_vals:
    base: [First, Second, Third, Home]

```

```
{% macro add_enums() %}
  {% set sql%}
    {% for enum, table in var("enum_lookups").items() %}
      CREATE TYPE {{ enum }} AS ENUM (SELECT DISTINCT {{ enum }} FROM {{ table }});
    {%- endfor %}
    {% for node in graph.sources.values() %}
      {% for col_name, col_data in node.columns.items() if col_data.get("data_type") %}
        ALTER TABLE {{ node.schema }}.{{ node.name }} ALTER COLUMN {{ col_name }} TYPE {{ col_data.data_type }};
      {%- endfor %}
    {% endfor %}
  {% endset %}
  {% do log(sql, info=True)%}
  {% do run_query(sql) %}
{% endmacro %}
```
